# ********************************************************************************
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

---
name: Build Autotriage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

env:
  TRIAGE_SCRIPT: "tooling/build_autotriage/build_autotriage.sh"

permissions:
  contents: read

jobs:
  autotriage:
    permissions:
      contents: read
      issues: write 
    runs-on: ubuntu-latest
    name: Run Build Triage
    if: ${{ (github.repository == 'adoptium/temurin-build') || (github.event_name == 'workflow_dispatch') }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Run Build Auto Triage"
        run: bash "${PWD}/${TRIAGE_SCRIPT}" jdk8u jdk11u jdk17u jdk21u jdk23u jdk24 jdk25head

      - name: Create Issue From File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        with:
          filename: ./build_triage_output.md
