# ********************************************************************************
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ********************************************************************************

name: Code Freeze Bot

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  codefreeze:
    uses: adoptium/.github/.github/workflows/code-freeze.yml@main
    secrets: inherit
