# Label and project adding bot, see .github/labeler.yml for config

name: "Labeller & Project Manager"
on:
  pull_request_target:
  issues:
  issue_comment:

jobs:
  Label:
    runs-on: ubuntu-latest
    name: Assign Labels
    steps:
    - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # v4.0.2
      if: ${{ github.event.pull_request }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: fuxingloh/multi-labeler@6704db0bcba106d07482efabbc79d3092af74fa2 # v2.0.3
      with:
        github-token: "${{secrets.GITHUB_TOKEN}}"
        config-path: .github/regex_labeler.yml
