---
name: TestSBOM

on:
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/testsbom.yml"
      - "cyclonedx-lib/**"

# Cancel existing runs if user makes another push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test_sbom_gen:
    name: gen_sbom
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # Build with jdk8 to ensure TemurinGenSBOM meets min compatibility
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        id: setup-java
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Build TemurinGenSBOM.java
        run: |
          ant -noinput -buildfile cyclonedx-lib/build.xml clean
          ant -noinput -buildfile cyclonedx-lib/build.xml build

      - name: Run TemurinGenSBOM Unit test
        run: ant -noinput -buildfile cyclonedx-lib/build.xml run

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        name: Collect and Archive TemurinGenSBOM Artifacts
        with:
          name: testSBOM
          path: cyclonedx-lib/build/testSBOM.json
